name: android-ci

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: '选择Build'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
          - aab
      upload-to-pgy:
        description: '上传到蒲公英'
        required: false
        type: boolean

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: ${{ inputs.build-type }}
      UPLOAD_TO_PGY: ${{ inputs.upload-to-pgy }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v1
        with:
          java-version: '17.x' # device_info_plus需要java17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build AAB
        if: env.BUILD_TYPE == 'aab'
        run: flutter build appbundle --release --split-debug-info=tmp/

      - name: Build release-apk
        if: env.BUILD_TYPE == 'release'
        run: flutter build apk --release --split-debug-info=tmp/

      - name: Build debug-apk
        if: env.BUILD_TYPE == 'debug'
        run: flutter build apk --debug --split-debug-info=tmp/

      - name: Archive production artifacts
        if: env.BUILD_TYPE == 'aab'
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Archive release artifacts
        if: env.BUILD_TYPE == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Archive debug artifacts
        if: env.BUILD_TYPE == 'debug'
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Set PGYER upload file path
        if: env.UPLOAD_TO_PGY == 'true'
        run: |
          if [[ "${{ env.BUILD_TYPE }}" == "aab" ]]; then
            echo "UPLOAD_FILE_PATH=build/app/outputs/bundle/release/app-release.aab" >> $GITHUB_ENV
          elif [[ "${{ env.BUILD_TYPE }}" == "release" ]]; then
            echo "UPLOAD_FILE_PATH=build/app/outputs/flutter-apk/app-release.apk" >> $GITHUB_ENV
          else
            echo "UPLOAD_FILE_PATH=build/app/outputs/flutter-apk/app-debug.apk" >> $GITHUB_ENV
          fi

      - name: Upload PGYER File
        if: env.UPLOAD_TO_PGY == 'true'
        uses: PGYER/pgyer-upload-app-action@v1.3
        with:
          _api_key: ${{ secrets.PGY_KEY }}
          appFilePath: ${{ env.UPLOAD_FILE_PATH }}
          buildUpdateDescription: '识别结果兼容第三方格式'
#        uses: xtayga/upload-pgyer-action@master
#        with:
#          url: https://www.pgyer.com/apiv2/app/upload
#          forms: '{"_api_key":"${{ secrets.PGY_KEY }}","buildName":"RSS"}'
#          fileForms: '{"file":"${{ env.UPLOAD_FILE_PATH }}"}'