name: iOS_ci2

on:
  workflow_dispatch:
    inputs:
      upload-to-testflight:
        description: '上传到App Store Connect'
        required: false
        type: boolean
      upload-to-pgy:
        description: '上传到蒲公英'
        required: false
        type: boolean

jobs:
  build-ios:
    name: build
    runs-on: macos-latest
    env:
      UPLOAD_TO_TESTFLIGHT: ${{ inputs.upload-to-testflight }}
      UPLOAD_TO_PGY: ${{ inputs.upload-to-pgy }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Restore packages
        run: flutter pub get

      - name: pod repo update
        run: pod repo update

      - name: flutter build ios
        if: env.UPLOAD_TO_PGY == 'true'
        uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: flutter build ipa --release --export-options-plist=ios/ExportOptions-debug.plist
          certificate-base64: ${{ secrets.P12_RELEASE_BASE64_DEBUG }}
          certificate-password: ${{ secrets.P12_PASSWORD_DEBUG }}
          provisioning-profile-base64: ${{ secrets.PROVISIONING_PROFILE_BASE64_DEBUG }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD_DEBUG }}

      - name: flutter build ios
        if: env.UPLOAD_TO_TESTFLIGHT == 'true'
        uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
          certificate-base64: ${{ secrets.P12_RELEASE_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.PROVISIONING_PROFILE_BASE64_RELEASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Archive IPA
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: build/ios/ipa/VideoAI.ipa

      - name: 'Upload file to test flight using CLI'
        if: env.UPLOAD_TO_TESTFLIGHT == 'true'
        run: |
          echo "Starting upload."
          xcrun altool --upload-app -t ios -f "build/ios/ipa/VideoAI.ipa" -u ${{ secrets.APPLEID_USERNAME }} -p ${{ secrets.APPLEID_PASSWORD }} --verbose

      - name: Upload PGYER File
        if: env.UPLOAD_TO_PGY == 'true'
        uses: PGYER/pgyer-upload-app-action@v1.3
        with:
          _api_key: ${{ secrets.PGY_KEY }}
          appFilePath: build/ios/ipa/VideoAI.ipa
          buildUpdateDescription: '~~~'
